# Generated by Django 5.1.7 on 2025-06-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_livro_autor_remove_livro_coautor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editora',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
